### ISSUE TITLE
Error when running in very minimal Alpine image

### ISSUE THREAD

**Issue by steven-collins-omega** [fpco/pid1#3]
In good bug report form I'll start with explaining what actually happened, but it's a long story; tl;dr, skip to the end to what I think is the probable cause.

I built an image based on the official Docker `alpine` image, following the example at https://www.fpcomplete.com/blog/2016/10/static-compilation-with-stack very closely (my goal being not to build `pid1` itself, but to produce a similarly small static executable for my app, and ultimately to _use_ `pid1`). The Dockerfile for this image includes the lines
```
ENV PID_1_VERSION 0.1.0.0
RUN curl -L \
    https://github.com/fpco/pid1/releases/download/v$PID_1_VERSION/pid1-$PID_1_VERSION-linux-x86_64.tar.gz \
    | tar -xzC /
```
 I built my app in this image, still closely following the blog post. (At this point I have an image called, say, `my-app-compiled`.)

Then I ran https://github.com/mvanholsteijn/strip-docker-image on the image I had at that point, which creates an image `FROM scratch` with only the necessary files (only a handful in this case), including my app, `/sbin/su-exec` and `/sbin/pid1`. This image is called `my-app-stripped`. Finally I create my final image with this Dockerfile:
```
FROM my-app-stripped:latest
EXPOSE 3000
USER root
ENTRYPOINT ["/sbin/pid1"]
CMD ["/sbin/su-exec", "my_user", "/bin/my_app"]
``` 

I expect that building and running this will start a container running my app, but actually the container exits immediately with the following error in the logs:
```
AUS-SCollins:furious scollins$ docker logs infallible_bohr
panic: standard_init_linux.go:175: exec user process caused "no such file or directory" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "no such file or directory"

goroutine 1 [running, locked to thread]:
panic(0x88f8a0, 0xc82013ae00)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8201072e8)
	/tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x88f8a0, 0xc82013ae00)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc820106bf8, 0xc82001e0a8, 0xc820106d08)
	/tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820069540, 0x7fc37d855698, 0xc82013ae00)
	/tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc820086a00, 0x0, 0x0)
	/tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x7f45a0, 0x9a4d88, 0x13, 0x8ebac8, 0x4, 0xc820107268, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x7f45a0, 0x9a4d88, 0x13, 0xc820107268, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x7f45a0, 0x9a4d88, 0xc820086a00, 0x0, 0x0)
	/tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x8ee970, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x984240, 0x51, 0x0, ...)
	/tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001800, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
	/tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/main.go:137 +0xe24
```

The cause would appear to be that at least the current released version of `/sbin/pid1` is not actually a statically-linked executable, and furthermore depends on libraries that are not present in Alpine:
```
AUS-SCollins:furious scollins$ docker run -it --entrypoint /bin/bash --user root my-app-compiled --login -i
4d034bddb7d6:/h/app# ldd /sbin/pid1
	/lib64/ld-linux-x86-64.so.2 (0x562bb0238000)
	librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x562bb0238000)
	libutil.so.1 => /lib64/ld-linux-x86-64.so.2 (0x562bb0238000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x562bb0238000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x7fd866d24000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x562bb0238000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x562bb0238000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fd866b11000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x562bb0238000)
Error relocating /sbin/pid1: pthread_setname_np: symbol not found
4d034bddb7d6:/h/app# find /lib* -name '*-linux-*'
4d034bddb7d6:/h/app#
```
Let me know if I can provide any more information.

**Comment by snoyberg** [comment]
@dysinger Did you end up uploading your statically compiled `pid1` exe to the releases?

**Comment by snoyberg** [comment]
I've published a new release with a static binary, can you give that a shot?

https://github.com/fpco/pid1/releases/tag/pid1%2F0.1.0.1

**Comment by steven-collins-omega** [comment]
Apologies for the delay, I've been very busy. I'm rebuilding my images with it right now.

**Comment by steven-collins-omega** [comment]
Yes, it seems to work now, thank you!

One minor comment -- the URL for the release is a bit awkward. The relevant part of my Dockerfile now looks like

```
ENV INIT /sbin/pid1
ENTRYPOINT ["/sbin/pid1"]
ENV PID_1_VERSION 0.1.0.1
ENV PID_1_FULL_VERSION pid1%2F$PID_1_VERSION
RUN curl -L \
    https://github.com/fpco/pid1/releases/download/$PID_1_FULL_VERSION/pid1-$PID_1_VERSION-linux-x86_64.tar.gz \
    | tar -xzC / && chmod 755 $INIT
```

**Comment by snoyberg** [comment]
I think we're stuck with most of that, though I suppose we could put a raw-executable version in the release as well, so you'd be able to do something like:


```
curl -L \
    https://github.com/fpco/pid1/releases/download/$PID_1_FULL_VERSION/pid1 > $INIT \
     && chmod 755 $INIT
```

You interested in that?
